name: Manual Trigger

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Which environment to deploy to'
        required: true
        default: 'production'

jobs:
  merge:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout main repository
        uses: actions/checkout@v2
        with:
          repository: kohicha/test-blog

      - name: Checkout staging repository
        uses: actions/checkout@v2
        with:
          repository: kohicha/content

      - name: Merge changes
        run: |
          cd test-blog
          git pull ../content main
          git push origin main
